In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
print(grades[0,1])
print(grades[2])
print(grades[0:2])
print(grades[[0, 2]])
print(grades[:, 1])
print(grades[:, 1:3])
print(grades[:, [0, 2]])
print(grades.mean(axis=0))
print(grades.mean(axis=1))

96
[94 77 90]
[[ 87  96  70]
 [100  87  90]]
[[87 96 70]
 [94 77 90]]
[96 87 77 81]
[[96 70]
 [87 90]
 [77 90]
 [81 82]]
[[ 87  70]
 [100  90]
 [ 94  90]
 [100  82]]
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]


In [3]:
numbers = np.array([100, 49, 324, 729, 91])
sqaureRoot = np.sqrt(numbers)
print(sqaureRoot)
print(sqaureRoot * 3)
print(np.multiply(sqaureRoot, 3))

[10.          7.         18.         27.          9.53939201]
[30.         21.         54.         81.         28.61817604]
[30.         21.         54.         81.         28.61817604]


In [8]:
x = np.arange(1, 10)
y = x.view()
print(x)
print(y)
x *= 5
print(x)
print(y)
y *= 2
print(x)
print(y)
z = x[0:5]
x[1] = 0
print(x)
print(z)
print(y)
z[2] = 0
print(x)
print(z)
print(y)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45]
[ 5 10 15 20 25 30 35 40 45]
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
[10  0 30 40 50 60 70 80 90]
[10  0 30 40 50]
[10  0 30 40 50 60 70 80 90]
[10  0  0 40 50 60 70 80 90]
[10  0  0 40 50]
[10  0  0 40 50 60 70 80 90]


In [10]:
p = np.arange(0,3)
q = p.copy()
print(p)
print(q)
p *= 10
print(p)
print(q)

[0 1 2]
[0 1 2]
[ 0 10 20]
[0 1 2]


In [12]:
examScores = np.array([[100, 92, 71], [82, 90, 62], [50, 89, 77]])
print(examScores)
print(examScores.reshape(1,9)) # shallow copy, does not change examScores, ravel
print(examScores)
print(examScores.resize(1,9)) # modifies examScores' shape, flatten
print(examScores)

[[100  92  71]
 [ 82  90  62]
 [ 50  89  77]]
[[100  92  71  82  90  62  50  89  77]]
[[100  92  71]
 [ 82  90  62]
 [ 50  89  77]]
None
[[100  92  71  82  90  62  50  89  77]]


In [13]:
examScores = np.array([[100, 92, 71], [82, 90, 62], [50, 89, 77]])
print(examScores)
print(examScores.T)
print(examScores)
examScores1 = np.array([[90, 92, 71], [50, 92, 77]])
print(np.vstack((examScores, examScores1)))
#print(np.hstack((examScores, examScores1)))
examScores1 = np.array([[90, 92, 71], [50, 92, 77], [32, 70, 53]])
print(np.hstack((examScores, examScores1)))

[[100  92  71]
 [ 82  90  62]
 [ 50  89  77]]
[[100  82  50]
 [ 92  90  89]
 [ 71  62  77]]
[[100  92  71]
 [ 82  90  62]
 [ 50  89  77]]
[[100  92  71]
 [ 82  90  62]
 [ 50  89  77]
 [ 90  92  71]
 [ 50  92  77]]
[[100  92  71  90  92  71]
 [ 82  90  62  50  92  77]
 [ 50  89  77  32  70  53]]
