In [6]:
import numpy as np
import pandas as pd

In [2]:
curve = np.ones(shape=(10,4), dtype=float)
print(curve)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
random_grades = np.random.randint(low=70, high=101, size=40)
exam_grades = random_grades.reshape((10, 4))
print(exam_grades)

[[ 81  88  89  74]
 [ 70  88  84  90]
 [ 78  75  88  76]
 [ 70  70  97  88]
 [ 92  90  81  81]
 [ 93  84  88  89]
 [ 84  82  85  70]
 [ 85  91  85 100]
 [ 71  76  71  75]
 [100  90  86  83]]


In [4]:
curved_grades = curve + exam_grades
print(curved_grades)

[[ 82.  89.  90.  75.]
 [ 71.  89.  85.  91.]
 [ 79.  76.  89.  77.]
 [ 71.  71.  98.  89.]
 [ 93.  91.  82.  82.]
 [ 94.  85.  89.  90.]
 [ 85.  83.  86.  71.]
 [ 86.  92.  86. 101.]
 [ 72.  77.  72.  76.]
 [101.  91.  87.  84.]]


In [5]:
print(curved_grades[:, 0])

[ 82.  71.  79.  71.  93.  94.  85.  86.  72. 101.]


In [7]:
df = pd.DataFrame(curved_grades)
print(df)

       0     1     2      3
0   82.0  89.0  90.0   75.0
1   71.0  89.0  85.0   91.0
2   79.0  76.0  89.0   77.0
3   71.0  71.0  98.0   89.0
4   93.0  91.0  82.0   82.0
5   94.0  85.0  89.0   90.0
6   85.0  83.0  86.0   71.0
7   86.0  92.0  86.0  101.0
8   72.0  77.0  72.0   76.0
9  101.0  91.0  87.0   84.0


In [8]:
df.rename(columns = {0:'Exam1', 1:'Exam2', 2:'Exam3', 3:'Exam4'}, inplace=True)
print(df)

   Exam1  Exam2  Exam3  Exam4
0   82.0   89.0   90.0   75.0
1   71.0   89.0   85.0   91.0
2   79.0   76.0   89.0   77.0
3   71.0   71.0   98.0   89.0
4   93.0   91.0   82.0   82.0
5   94.0   85.0   89.0   90.0
6   85.0   83.0   86.0   71.0
7   86.0   92.0   86.0  101.0
8   72.0   77.0   72.0   76.0
9  101.0   91.0   87.0   84.0


In [10]:
df.rename({0:'Andy', 1:'Barbara',  2:'David', 3:'Emily', 4:'Frank', 5:'Grace', 6:'Heidi', 7:'Ivan', 8:'Janet', 9:'Charlie'}, inplace=True)
print(df)

         Exam1  Exam2  Exam3  Exam4
Andy      82.0   89.0   90.0   75.0
Barbara   71.0   89.0   85.0   91.0
David     79.0   76.0   89.0   77.0
Emily     71.0   71.0   98.0   89.0
Frank     93.0   91.0   82.0   82.0
Grace     94.0   85.0   89.0   90.0
Heidi     85.0   83.0   86.0   71.0
Ivan      86.0   92.0   86.0  101.0
Janet     72.0   77.0   72.0   76.0
Charlie  101.0   91.0   87.0   84.0


In [11]:
print(df.Exam4)

Andy        75.0
Barbara     91.0
David       77.0
Emily       89.0
Frank       82.0
Grace       90.0
Heidi       71.0
Ivan       101.0
Janet       76.0
Charlie     84.0
Name: Exam4, dtype: float64


In [12]:
print(df.loc['Ivan'])

Exam1     86.0
Exam2     92.0
Exam3     86.0
Exam4    101.0
Name: Ivan, dtype: float64
